<?php

return array(
	'TOP_NAV' => array(
		'MYHOME_NAV' 	=> 	'我的主页',
		'ATTENDANCE_NAV'=> 	'考勤',
//		'PROJECT_NAV'	=>	'项目',
//		'PRODUCT_NAV'	=> 	'产品',
		'TASK_NAV'		=>	'任务',
		'REPORT_NAV'	=>	'统计',
		'ADMIN_NAV'		=>	'后台',
		'ABOUT_NAV'		=>	'关于'
	),

	'MENU'	=>	array(
		'COMMONTASKS_MENU'		=>	'通用',
		'TASK_MENU'				=>	'研发',
		'SALESTASK_MENU'		=>	'销售',
		'PROCUREMENTTASK_MENU'	=>	'采购',
        'PRODUCTIVE_TASK_MENU' 	=>  '生产',
        'BUSINESS_TASK_MENU' 	=>  '商务',
        'MARKET_TASK_MENU'		=>  '市场',
		'PRODUCT_MANAGER_MENU'	=>	'产品委员会',
		'SUPPLY_COMMISSION_MENU'=>	'供应委员会',
		'PRODUCT_MANAGING_MENU'	=>	'产品经理',
		'MATERIEL_PLANNING_MENU'=>  '物控计划',
		'MDC_MENU'				=>  'MDC',
		'EXAMTASK_MENU'			=>	'考试',
		'QUESTIONNAIRETASK_MENU'=>	'问卷调查',
		'ATTRIBUTEMAINTAIN_TASK_MENU'=>	'属性维护',
// 		'DEMAND_MENU'			=>	'需求',
// 		'BUG'					=>	'BUG',
// 		'ORIGINALDEMAND_MENU'	=>	'原始需求',
		'USER_MENU'				=>	'用户',
		'DEPARTMENT_MENU'		=>	'组织架构',
		'ATTENDANCESET_MENU'	=>	'考勤',
		'BUSMANAGE_MENU'		=>	'班车',
		'NOTICE_MENU'			=>	'公告',
		'ACCESS_FUNCTIONAL_MENU'			=>	'权限',
//		'NODE_MENU'				=>	'节点',
		'MYHOME_INDEX_MENU'		=>	'首页',
		'MYHOME_COMMONTASKS_MENU'=>	'我的任务',
		'MYHOME_TASK_MENU'		=>	'我的研发任务',
// 		'MYHOME_DEMAND_MENU'	=>	'我的需求',
// 		'MYHOME_BUG_MENU'		=>	'我的Bug',
// 		'MYHOME_ORIGINALDEMAND_MENU' =>	'我的原始需求',
		'MYHOME_ACTIONS_MENU'	=>	'我的动态',
		'MYHOME_CUSTOMIZE_GROUP'=> '我的用户群组',
		'MYHOME_DEPT_MENU'		=>	'考核成员',
		'MYHOME_PENDING_MENU'	=>	'协同审批',
		'MYHOME_USERCENTER_MNU'	=>	'个人中心',
        'MYHOME_MESSAGE_MNU'	=>	'站内信',
        'MYHOME_NOTICE_MNU'	    =>	'公告',
        'MYHOME_HELPCENTER_MNU'	=>	'帮助中心',
		'ATTENDANCE_MENU'		=>	'考勤',
		'ASKFORLEAVE_MENU'		=>	'请假',
		'CHANGEREST_MENU'		=>	'调休',
		'LATERADDSIGN_MENU'		=>	'补签',
		'JOURNAL_MENU'			=>	'工作日志',
		'BUS_MENU'				=>	'班车',
		'SCHEDUMING_MENU'		=>	'工作排班表',
		'TASK_REPORT_MENU'		=>	'任务',
		'ATTENDANCE_REPORT_MENU'=>	'考勤',
		'ASKLEAVE_REPORT_MENU'	=>	'请假',
		'REPORT_CHANGEREST_MENU' =>	'调休',
		'REPORT_JOURNALCHECK_MENU' =>'日志',
		'BUS_APPLY_REPORT_MENU' => '班车',
		'ADMIN_TASK_MENU'		=>'任务',
// 		'PROJECT_MENU' => '项目',
// 		'PREPARE_PROJECT_MENU' => '预研项目'
		'BUSINESS_DATA_REPORT_MENU'	=>'业务数据',
		'UPDATE_HISTORY_MENU' 		=>'更新记录',
		'MATERIEL_PACKAGE_MENU' 	=>'物料套包',
	),

	'THIRD_MENU' => array(
		'COMMON_TASKS_THIRD_MENU'				=>	'通用任务',
		'REGULAR_TASKS_THIRD_MENU'				=>	'定时任务',
		'ACCESS_APPLY_TASKS_THIRD_MENU'			=>	'权限申请',
		'ENTRUST_TASKS_THIRD_MENU'				=>	'任务委托',
		
		'TASK_THIRD_MENU'						=>	'任务',
		'DEMAND_THIRD_MENU'						=>	'需求',
		'BUG_THIRD_MENU'						=>	'BUG',
		'ORIGINALDEMAND_THIRD_MENU'				=>	'原始需求',
		'PROJECT_THIRD_MENU' 					=> 	'项目',
		'PREPARE_PROJECT_THIRD_MENU'			=> 	'预研项目',


		'PRODUCT_THIRD_MENU'					=>	'产品',
		'EXAM_TASK_MANAGE_MENU'					=>	'考试',
		'QUESTIONNAIR_TASK_THIRD_MENU'			=>	'问卷调查',
		'OBJECT_ATTR_THIRD_MENU'				=>	'属性',

		'MATERIEL_PACKAGE_THIRD_MENU'			=>	'物料套包',
		'MATERIEL_PACKAGE_CATE_THIRD_MENU'		=>	'套包分类',
//		'EXAM_TASK_MANAGE_MENU'					=>	'考试',

		'EXAM_TASK_THIRD_MENU'					=> 	'考试',
		'ENTRY_EXAN_QUESTION_THIRD_MENU'		=> 	'录试题',
		'QUESTIONNAIRE_TASK_THIRD_MENU'			=> 	'问卷调查',
		'ENTRY_QUESTIONNAIRE_THIRD_MENU'		=> 	'录问卷题',
			
		'MYHOME_TASK_THIRD_MENU'				=>	'我的研发任务',
		'MYHOME_DEMAND_THIRD_MENU'				=>	'我的需求',
		'MYHOME_BUG_THIRD_MENU'					=>	'我的Bug',
		'MYHOME_ORIGINALDEMAND_THIRD_MENU'		=>	'我的原始需求',

		'REPORT_JOURNAL_CHECK'             		=>  '日志检查',
		'JOURNALCHECK_REVIEW_THIRD_MENU'        =>  '日志统计',
			
		'USER_CENTER_THIRD_MENU'				=> '基本信息',
		'ENTRUST_THIRD_MENU'					=> '委托管理',
		
		'BUS_CIRCUIT'                           =>  '班车路线',
		'BUS_APPLY'                             =>  '班车申请',
		
		'REPORT_COMMONTASK_MENU'        		=>  '通用任务',
		'REPORT_TASK_MENU'             			=>  '研发任务',
		'REPORT_SALESTASKS_MENU'             	=>  '销售任务',
        'REPORT_PROCUREMENT_MENU'               =>  '采购任务',

		'SALES_DATA_REPORT_MENU'				=>	'产品出货预测',
		'PURCHASING_DATA_REPORT_MENU'			=>	'物料采购预测',
		'PRODUCT_TEMP_FORECAST_REPORT_MENU'		=>	'临时预测统计',
		'MATERIEL_SALE_FORECAST_REPORT_MENU'	=>	'物料出货预测',
		// 'PRODUCT_PURCHASE_FORECAST_REPORT_MENU'	=>	'产品外购预测',
		'SALESMAN_PURCHASE_FORECAST_REPORT_MENU'	=>	'销售员出货预测',
		'CUSTOMER_PURCHASE_FORECAST_REPORT_MENU'	=>	'客户出货预测',

		'DEPARTMENT_THIRD_MENU' 				=>	'职能部门',
		'BUSINESS_THIRD_MENU' 					=>	'业务组织',
		'PROFESSION_THIRD_MENU' 				=>	'专业岗位',
		
		'PRODUCTFORECAST_THIRD_MENU'			=> 	'生产预测',
		'PRODUCT_FORECAST_REPORT_MENU'			=>	'生产预测汇总',
		'PRODUCTIVE_THIRD_MENU'					=> 	'生产任务反馈',
		'PRODUCTIVEREPORT_THIRD_MENU'			=> 	'生产任务汇总',
		'PRODUCTIVEMAINTENANCE_THIRD_MENU'		=> 	'生产属性维护',

		'BUSINESS_SUPPLY_DEMAND_INFO_MENU'		=> 	'产品供需查询',
		'BUSINESS_SHIPPING_RESERVATION_MENU'	=> 	'供需预约跟踪',
		'BUSINESS_RESERVATION_INTERVENE_MENU'	=> 	'产品供需干预',
		'CUSTOMER_BUSINESS_RELATIONSHIP_MENU'	=> 	'商务客户管理',

        'PRODUCT_VERSION_MENU'                  =>   '产品版本维护',
        'MATERIEL_PLANNING_THIRD_MENU'          =>   '物控计划干预',
		'MATERIEL_RELATION_MENU'				=>   '模组模块关系',
		'MATERIEL_RELATION_AA_MENU'				=>   '替代料维护',
		'MATERIEL_PRODUCT_DELIVERY_DATE_MENU'   =>   '物料生产交期',
		'MATERIEL_THIRD_MENU'					=> 	'物料新增申请',
		'MATERIEL_IMPORT_THIRD_MENU'			=> 	'物料导入申请',
		'DECISION_IMPORT_THIRD_MENU'			=> 	'采购商务策略',

		'PRODUCT_BOARD_CHANGE_MENU'				=>	 '产品委员会干预',
		'CONTROL_MATERIEL_REPORT_MENU'			=>	 '管控物料汇总',
		'SALE_PRODUCT_CHANGE_REPORT_MENU'		=>	 '产品干预汇总',
		'CONTROL_MATERIEL_EDIT_THIRD_MENU'      =>   '管控物料配置',

		'PRODUCT_MANAGER_THIRD_MENU' 			=>   '产品经理干预',
		'BATCH_PRODUCT_THIRD_MENU' 				=>   '产品批量试生产',

		'SALE_PRODUCT_CHANGE_REPORT_MDC_MENU'	=>	 '产品干预汇总',
		'CONTROL_MATERIEL_REPORT_MDC_MENU'		=>   '管控物料汇总',

		'SALESTASK_THIRD_MENU'					=>   '下月出货预测',
		'SALESTASK_DEMAND_THIRD_MENU'			=>   '产品供需查询',
		'SALES_SHIPPING_RESERVATION_MENU'		=>   '供需预约跟踪',
		'SALES_PRODUTION_OFFER_MENU'			=>    '产品报价',
		'SALES_PRODUTION_PRICE_MENU'			=>    '产品定价',
		'SALES_PRODUTION_ATTR_MENU'				=>    '产品规格维护',
		'SALES_PRODUTION_ADD_MENU'				=>    '产品新增',
		'SALES_PRODUCT_REPORT_MENU'				=>    '销售型号汇总',

        'PRODUCT_ATTRIBUTES_GROUP_MENU'			=>    '属性项维护',
		'SALES_PRODUTION_CATEGORY_MENU'			=>    '属性项配置',
		'ATTRIBUTE_EDIT_REPORT_MENU'			=>    '属性维护汇总',
		'ATTRIBUTE_CONFIG_REPORT_MENU'			=>    '属性配置汇总',
		'PROCUREMENT_TASK_MENU' 				=>    '采购预测',
		'PROCUREMENT_TRACK_MENU' 				=>    '采购跟踪',
		'PROCUREMENT_TRACK_REPORT_MENU' 		=>    '采购跟踪汇总',
		'SUPPLIER_SALESMAN_RELATION_MENU' 		=>    '业务员配置',
		'PROCUREMENT_REPORT_THIRD_MENU'      	=>   '采购预测汇总',

		'ACCESS_FUNCTIONAL_THIRD_MENU'      	=>   '功能配置',
		'ACCESS_ROLE_THIRD_MENU'      			=>   '角色配置',
    ),

	'CONTROLLER' => array(
		'COMMONTASKS'		=>	array('nav'	=> 'TASK_NAV', 'menu' => 'COMMONTASKS_MENU', 'third_menu' => 'COMMON_TASKS_THIRD_MENU'),
		'REGULARCOMMONTASKS'=>	array('nav'	=> 'TASK_NAV', 'menu' => 'COMMONTASKS_MENU', 'third_menu' => 'REGULAR_TASKS_THIRD_MENU'),
		'ACCESSAPPLYTASKS'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'COMMONTASKS_MENU', 'third_menu' => 'ACCESS_APPLY_TASKS_THIRD_MENU'),
		'ENTRUSTTASKS'		=>	array('nav'	=> 'TASK_NAV', 'menu' => 'COMMONTASKS_MENU', 'third_menu' => 'ENTRUST_TASKS_THIRD_MENU'),
		
		'TASK'				=>	array('nav' => 'TASK_NAV', 'menu' => 'TASK_MENU', 'third_menu' => 'TASK_THIRD_MENU'),
		'DEMAND'			=>	array('nav'	=> 'TASK_NAV', 'menu' => 'TASK_MENU', 'third_menu' => 'DEMAND_THIRD_MENU'),
		'BUG'				=>	array('nav'	=> 'TASK_NAV', 'menu' => 'TASK_MENU', 'third_menu' => 'BUG_THIRD_MENU'),
		'ORIGINALDEMAND'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'TASK_MENU', 'third_menu' => 'ORIGINALDEMAND_THIRD_MENU'),
		'PROJECT'			=>	array('nav'	=> 'TASK_NAV', 'menu' => 'TASK_MENU', 'third_menu' => 'PROJECT_THIRD_MENU'),
		'PREPAREPROJECT'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'TASK_MENU', 'third_menu' => 'PREPARE_PROJECT_THIRD_MENU'),
		'EXAMTASK'			=>	array('nav' => 'TASK_NAV', 'menu' => 'EXAMTASK_MENU', 'third_menu' => 'EXAM_TASK_THIRD_MENU'),
		'ENTRYEXAMQUESTION'	=>	array('nav' => 'TASK_NAV', 'menu' => 'EXAMTASK_MENU', 'third_menu' => 'ENTRY_EXAN_QUESTION_THIRD_MENU'),
		'QUESTIONNAIRETASK'	=>	array('nav' => 'TASK_NAV', 'menu' => 'QUESTIONNAIRETASK_MENU', 'third_menu' => 'QUESTIONNAIRE_TASK_THIRD_MENU'),
		'ENTRYQUESTIONNAIR'	=>	array('nav' => 'TASK_NAV', 'menu' => 'QUESTIONNAIRETASK_MENU', 'third_menu' => 'ENTRY_QUESTIONNAIRE_THIRD_MENU'),
		'SALESTASKS'		=>	array('nav'	=> 'TASK_NAV', 'menu' => 'SALESTASK_MENU', 'third_menu' => 'SALESTASK_THIRD_MENU'),
		'SALESTASKSADINFO'		=>	array('nav'	=> 'TASK_NAV', 'menu' => 'SALESTASK_MENU', 'third_menu' => 'SALESTASK_DEMAND_THIRD_MENU'),
		'SALESRESERVATION'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'SALESTASK_MENU', 'third_menu' => 'SALES_SHIPPING_RESERVATION_MENU'),
		'SALESPRODUCTIONOFFER'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'SALESTASK_MENU', 'third_menu' => 'SALES_PRODUTION_OFFER_MENU'),
		'SALESPRODUCTIONPRICE'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'MARKET_TASK_MENU', 'third_menu' => 'SALES_PRODUTION_PRICE_MENU'),
		'SALESPRODUCTIONATTR'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'MARKET_TASK_MENU', 'third_menu' => 'SALES_PRODUTION_ATTR_MENU'),
		'SALESPRODUCTIONADD'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'MARKET_TASK_MENU', 'third_menu' => 'SALES_PRODUTION_ADD_MENU'),
		'SALESPRODUCTREPORT'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'MARKET_TASK_MENU', 'third_menu' => 'SALES_PRODUCT_REPORT_MENU'),
		'PROCUREMENTTASKS'		=>	array('nav'	=> 'TASK_NAV', 'menu' => 'PROCUREMENTTASK_MENU', 'third_menu' => 'PROCUREMENT_TASK_MENU'),
		'PROCUREMENTTRACK'		=>	array('nav'	=> 'TASK_NAV', 'menu' => 'PROCUREMENTTASK_MENU', 'third_menu' => 'PROCUREMENT_TRACK_MENU'),
		'PROCUREMENTTRACKREPORT'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'PROCUREMENTTASK_MENU', 'third_menu' => 'PROCUREMENT_TRACK_REPORT_MENU'),
        'SUPPLIERSALESMANRELATION'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'PROCUREMENTTASK_MENU', 'third_menu' => 'SUPPLIER_SALESMAN_RELATION_MENU'),
		'PROCUREMENTREPORT'	=>	array('nav' => 'TASK_NAV', 'menu' => 'PROCUREMENTTASK_MENU', 'third_menu' => 'PROCUREMENT_REPORT_THIRD_MENU'),

		'PRODUCTMANAGER'	=>	array('nav' => 'TASK_NAV', 'menu' => 'PRODUCT_MANAGER_MENU', 'third_menu' => 'PRODUCT_BOARD_CHANGE_MENU'),
		'CONTROLMATERIELREPORT'	=>	array('nav' => 'TASK_NAV', 'menu' => 'SUPPLY_COMMISSION_MENU', 'third_menu' => 'CONTROL_MATERIEL_REPORT_MENU'),
		'SALEPRODUCTCHANGEREPORT'	=>	array('nav' => 'TASK_NAV', 'menu' => 'SUPPLY_COMMISSION_MENU', 'third_menu' => 'SALE_PRODUCT_CHANGE_REPORT_MENU'),
		'CONTROLMATERIEL'	=>	array('nav' => 'TASK_NAV', 'menu' => 'SUPPLY_COMMISSION_MENU', 'third_menu' => 'CONTROL_MATERIEL_EDIT_THIRD_MENU'),
		'MATERIELRELATIONAA'	=>	array('nav' => 'TASK_NAV', 'menu' => 'SUPPLY_COMMISSION_MENU', 'third_menu' => 'MATERIEL_RELATION_AA_MENU'),
		'MATERIEL'			=>	array('nav'	=> 'TASK_NAV', 'menu' => 'SUPPLY_COMMISSION_MENU', 'third_menu' => 'MATERIEL_THIRD_MENU'),
		'MATERIELIMPORT'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'SUPPLY_COMMISSION_MENU', 'third_menu' => 'MATERIEL_IMPORT_THIRD_MENU'),
		'DECISIONIMPORT'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'SUPPLY_COMMISSION_MENU', 'third_menu' => 'DECISION_IMPORT_THIRD_MENU'),
			
		'PRODUCTMANAGING'	=>	array('nav' => 'TASK_NAV', 'menu' => 'PRODUCT_MANAGING_MENU', 'third_menu' => 'PRODUCT_MANAGER_THIRD_MENU'),
		'BATCHPRODUCT'		=>	array('nav' => 'TASK_NAV', 'menu' => 'PRODUCT_MANAGING_MENU', 'third_menu' => 'BATCH_PRODUCT_THIRD_MENU'),

		'CONTROLMATERIELREPORTMDC'	=>	array('nav' => 'TASK_NAV', 'menu' => 'MDC_MENU', 'third_menu' => 'CONTROL_MATERIEL_REPORT_MDC_MENU'),
		'SALEPRODUCTCHANGEREPORTMDC'	=>	array('nav' => 'TASK_NAV', 'menu' => 'MDC_MENU', 'third_menu' => 'SALE_PRODUCT_CHANGE_REPORT_MDC_MENU'),

		'MATERIELPLANNING'	=>	array('nav' => 'TASK_NAV', 'menu' => 'MATERIEL_PLANNING_MENU', 'third_menu' => 'MATERIEL_PLANNING_THIRD_MENU'),
		'MATERIELRELATION'	=>	array('nav' => 'TASK_NAV', 'menu' => 'MATERIEL_PLANNING_MENU', 'third_menu' => 'MATERIEL_RELATION_MENU'),
		'MATERIELPRODUCTDELIVERYDATE'   =>  array('nav' => 'TASK_NAV', 'menu' => 'MATERIEL_PLANNING_MENU', 'third_menu' => 'MATERIEL_PRODUCT_DELIVERY_DATE_MENU'),
			
        // 'PRODUCTVERSION'	=>	array('nav' => 'TASK_NAV', 'menu' => 'MATERIEL_PLANNING_MENU', 'third_menu' => 'PRODUCT_VERSION_MENU'),
        // 'PROVERSIONMAINTAIN'	=>	array('nav' => 'TASK_NAV', 'menu' => 'MATERIEL_PLANNING_MENU', 'third_menu' => 'PRODUCT_VERSION_MENU'),
		
		'PRODUCTFORECAST'   =>  array('nav'	=> 'TASK_NAV', 'menu' => 'PRODUCTIVE_TASK_MENU', 'third_menu' => 'PRODUCTFORECAST_THIRD_MENU'),	//生产预测
        'PRODUCTIVETASK'    =>  array('nav'	=> 'TASK_NAV', 'menu' => 'PRODUCTIVE_TASK_MENU', 'third_menu' => 'PRODUCTIVE_THIRD_MENU'),
        'PRODUCTIVETASKMAINTENANCE'    =>  array('nav'	=> 'TASK_NAV', 'menu' => 'PRODUCTIVE_TASK_MENU', 'third_menu' => 'PRODUCTIVEMAINTENANCE_THIRD_MENU'),
        'PRODUCTIVEREPORT'    =>  array('nav'	=> 'TASK_NAV', 'menu' => 'PRODUCTIVE_TASK_MENU', 'third_menu' => 'PRODUCTIVEREPORT_THIRD_MENU'),
		'PRODUCTFORECASTREPORT'=>	array('nav'	=> 'TASK_NAV', 'menu'	=> 'PRODUCTIVE_TASK_MENU', 'third_menu' => 'PRODUCT_FORECAST_REPORT_MENU' ),

		'BUSINESSSADINFO'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'BUSINESS_TASK_MENU', 'third_menu' => 'BUSINESS_SUPPLY_DEMAND_INFO_MENU'),//产品供需查询
        'BUSINESSRESERVATION' =>  array('nav'	=> 'TASK_NAV', 'menu' => 'BUSINESS_TASK_MENU', 'third_menu' => 'BUSINESS_SHIPPING_RESERVATION_MENU'),	//产品供需预约跟踪
        'BUSINESSINTERVENE' =>  array('nav'	=> 'TASK_NAV', 'menu' => 'BUSINESS_TASK_MENU', 'third_menu' => 'BUSINESS_RESERVATION_INTERVENE_MENU'),	//产品供需干预
		'CUSTOMBUSINESSRELATION' =>  array('nav'	=> 'TASK_NAV', 'menu' => 'BUSINESS_TASK_MENU', 'third_menu' => 'CUSTOMER_BUSINESS_RELATIONSHIP_MENU'),	//客户商务关系


        'USER'				=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'USER_MENU'),
		'DEPARTMENT'		=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'DEPARTMENT_MENU', 'third_menu' => 'DEPARTMENT_THIRD_MENU'),
		'BUSINESS'			=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'DEPARTMENT_MENU', 'third_menu' => 'BUSINESS_THIRD_MENU'),
		'PROFESSION'		=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'DEPARTMENT_MENU', 'third_menu' => 'PROFESSION_THIRD_MENU'),
		'NOTICE'			=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'NOTICE_MENU'),
		'ACCESSFUNCTIONAL'	=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'ACCESS_FUNCTIONAL_MENU'),
		'BUSMANAGE'			=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'BUSMANAGE_MENU'),
		'ATTENDANCESET'		=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'ATTENDANCESET_MENU'),
		'EXAMTYPE'		=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'ADMIN_TASK_MENU', 'third_menu' => 'EXAM_TASK_THIRD_MENU'),
		'QUESTIONNAIREMANAGE'	=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'ADMIN_TASK_MENU', 'third_menu' => 'QUESTIONNAIR_TASK_THIRD_MENU'),
		'PRODUCT'			=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'ADMIN_TASK_MENU', 'third_menu' => 'PRODUCT_THIRD_MENU'),
		'OBJECTATTR'			=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'ADMIN_TASK_MENU', 'third_menu' => 'OBJECT_ATTR_THIRD_MENU'),
//		'NODE'				=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'NODE_MENU'),

		'MATERIELPACKAGE'			=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'MATERIEL_PACKAGE_MENU', 'third_menu' => 'MATERIEL_PACKAGE_THIRD_MENU'),
		'MATERIELPACKAGECATE'		=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'MATERIEL_PACKAGE_MENU', 'third_menu' => 'MATERIEL_PACKAGE_CATE_THIRD_MENU'),

		'INDEX'				=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_INDEX_MENU'),
		'MYCOMMONTASKS'		=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_COMMONTASKS_MENU'),
		'MYTASK'			=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_TASK_MENU', 'third_menu' => 'MYHOME_TASK_THIRD_MENU'),
		'MYDEMAND'			=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_TASK_MENU', 'third_menu' => 'MYHOME_DEMAND_THIRD_MENU'),
		'MYBUG'				=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_TASK_MENU', 'third_menu' => 'MYHOME_BUG_THIRD_MENU'),
		'MYORIGINALDEMAND'	=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_TASK_MENU', 'third_menu' => 'MYHOME_ORIGINALDEMAND_THIRD_MENU'),
		'MYACTIONS'			=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_ACTIONS_MENU'),
		'MYCUSTOMIZEGROUP'	=>	array('nav' => 'MYHOME_NAV', 'menu' => 'MYHOME_CUSTOMIZE_GROUP'),
		'MYDEPARTMENT'		=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_DEPT_MENU'),
		'JOURNALCHECK'		=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_DEPT_MENU'),
		'MYPENDING'			=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_PENDING_MENU'),
			
		'USERCENTER'	=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_USERCENTER_MNU', 'third_menu' => 'USER_CENTER_THIRD_MENU'),
		'ENTRUSTMANAGE'		=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_USERCENTER_MNU', 'third_menu' => 'ENTRUST_THIRD_MENU'),
			
		'MESSAGE'		    =>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_MESSAGE_MNU'),
		'HOMENOTICE'		=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_NOTICE_MNU'),
		'HELPCENTER'		=>	array('nav'	=> 'MYHOME_NAV', 'menu' => 'MYHOME_HELPCENTER_MNU'),
		
		'COMMONTASKREPORT'	=>	array('nav'	=> 'REPORT_NAV', 'menu' => 'TASK_REPORT_MENU', 'third_menu' => 'REPORT_COMMONTASK_MENU'),
		'TASKREPORT'		=>	array('nav'	=> 'REPORT_NAV', 'menu' => 'TASK_REPORT_MENU', 'third_menu' => 'REPORT_TASK_MENU'),
		'SALESTASKSREPORT'	=>	array('nav'	=> 'REPORT_NAV', 'menu' => 'TASK_REPORT_MENU', 'third_menu' => 'REPORT_SALESTASKS_MENU'),
        'PROCUREMENTTASKSREPORT'=>	array('nav'	=> 'REPORT_NAV', 'menu' => 'TASK_REPORT_MENU', 'third_menu' => 'REPORT_PROCUREMENT_MENU'),
        'ATTENDANCEREPORT'	=>	array('nav'	=> 'REPORT_NAV', 'menu'	=> 'ATTENDANCE_REPORT_MENU'),
		'REPORTCHANGEREST'	=>	array('nav'	=> 'REPORT_NAV', 'menu' => 'REPORT_CHANGEREST_MENU'),
		'REPORTJOURNALCHECK'=>	array('nav'	=> 'REPORT_NAV', 'menu'	=> 'REPORT_JOURNALCHECK_MENU', 'third_menu' => 'REPORT_JOURNAL_CHECK' ),
		'ASKLEAVEREPORT'	=>	array('nav'	=> 'REPORT_NAV', 'menu'	=> 'ASKLEAVE_REPORT_MENU'),
		'BUSREPORT'			=>	array('nav' => 'REPORT_NAV', 'menu' => 'BUS_APPLY_REPORT_MENU'),
		'JOURNALREVIEW'     =>  array('nav'	=> 'REPORT_NAV', 'menu'	=> 'REPORT_JOURNALCHECK_MENU', 'third_menu' => 'JOURNALCHECK_REVIEW_THIRD_MENU'),
		
		'PRODUCTSALESREPORT'=>	array('nav'	=> 'REPORT_NAV', 'menu'	=> 'BUSINESS_DATA_REPORT_MENU', 'third_menu' => 'SALES_DATA_REPORT_MENU' ),
		'MATERIELSALEFORECASTREPORT'=>	array('nav'	=> 'REPORT_NAV', 'menu'	=> 'BUSINESS_DATA_REPORT_MENU', 'third_menu' => 'MATERIEL_SALE_FORECAST_REPORT_MENU' ),
		'PRODUCTTEMPFORECAST'=>	array('nav'	=> 'REPORT_NAV', 'menu'	=> 'BUSINESS_DATA_REPORT_MENU', 'third_menu' => 'PRODUCT_TEMP_FORECAST_REPORT_MENU' ),
		'MATERIALPURCHASEREPORT'=>	array('nav'	=> 'REPORT_NAV', 'menu'	=> 'BUSINESS_DATA_REPORT_MENU', 'third_menu' => 'PURCHASING_DATA_REPORT_MENU' ),
		// 'PRODUCTPURCHASEREPORT'=>	array('nav'	=> 'REPORT_NAV', 'menu'	=> 'BUSINESS_DATA_REPORT_MENU', 'third_menu' => 'PRODUCT_PURCHASE_FORECAST_REPORT_MENU' ),
		'SALESMANPURCHASEREPORT'=>	array('nav'	=> 'REPORT_NAV', 'menu'	=> 'BUSINESS_DATA_REPORT_MENU', 'third_menu' => 'SALESMAN_PURCHASE_FORECAST_REPORT_MENU' ),
		'CUSTOMERPURCHASEREPORT'=>	array('nav'	=> 'REPORT_NAV', 'menu'	=> 'BUSINESS_DATA_REPORT_MENU', 'third_menu' => 'CUSTOMER_PURCHASE_FORECAST_REPORT_MENU' ),
		'UPDATEHISTORY'=>	array('nav'	=> 'ABOUT_NAV', 'menu'	=> 'UPDATE_HISTORY_MENU'),

		'ATTENDANCE'		=>	array('nav'	=> 'ATTENDANCE_NAV', 'menu'	=> 'ATTENDANCE_MENU'),
		'SCHEDUMING'		=>	array('nav'	=> 'ATTENDANCE_NAV', 'menu'	=> 'SCHEDUMING_MENU'),
		'ASKLEAVE'			=>	array('nav'	=> 'ATTENDANCE_NAV', 'menu'	=> 'ASKFORLEAVE_MENU'),
		'LATERADDSIGN'		=>	array('nav'	=> 'ATTENDANCE_NAV', 'menu'	=> 'LATERADDSIGN_MENU'),
		'CHANGEREST'		=>	array('nav'	=> 'ATTENDANCE_NAV', 'menu'	=> 'CHANGEREST_MENU'),
		'JOURNAL'			=>	array('nav'	=> 'ATTENDANCE_NAV', 'menu'	=> 'JOURNAL_MENU'),
		'BUSCIRCUIT'        =>  array('nav' => 'ATTENDANCE_NAV', 'menu' => 'BUS_MENU' , 'third_menu' => 'BUS_CIRCUIT'),
		'BUS'				=>	array('nav' => 'ATTENDANCE_NAV', 'menu' => 'BUS_MENU' , 'third_menu' => 'BUS_APPLY'),

        'PRODUCTATTRIBUTESGROUP'	=>	array('nav'	=> 'TASK_NAV', 'menu' => 'ATTRIBUTEMAINTAIN_TASK_MENU', 'third_menu' => 'PRODUCT_ATTRIBUTES_GROUP_MENU'),
        'SALESPRODUCTCATEGORY'		=>	array('nav'	=> 'TASK_NAV', 'menu' => 'ATTRIBUTEMAINTAIN_TASK_MENU', 'third_menu' => 'SALES_PRODUTION_CATEGORY_MENU'),
        'ATTRIBUTEEDITREPORT'		=>	array('nav'	=> 'TASK_NAV', 'menu' => 'ATTRIBUTEMAINTAIN_TASK_MENU', 'third_menu' => 'ATTRIBUTE_EDIT_REPORT_MENU'),
        'ATTRIBUTECONFIGREPORT'		=>	array('nav'	=> 'TASK_NAV', 'menu' => 'ATTRIBUTEMAINTAIN_TASK_MENU', 'third_menu' => 'ATTRIBUTE_CONFIG_REPORT_MENU'),

		'ACCESSFUNCTIONAL'		=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'ACCESS_FUNCTIONAL_MENU', 'third_menu' => 'ACCESS_FUNCTIONAL_THIRD_MENU'),
		'ACCESSROLE'			=>	array('nav'	=> 'ADMIN_NAV', 'menu' => 'ACCESS_FUNCTIONAL_MENU', 'third_menu' => 'ACCESS_ROLE_THIRD_MENU'),
    )
);